# Generated by Django 3.2 on 2021-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210530_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], default='in_stock', max_length=100),
        ),
    ]
