# Generated by Django 3.2 on 2021-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_status',
            field=models.CharField(choices=[('INSTOCK', 'In stock'), ('OUTOFSTOCK', 'Out of stock'), ('LOWSTOCK', 'Low stock')], default='INSTOCK', max_length=100),
        ),
    ]
